crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('facturas/', include('facturas.urls', namespace="facturas")),
    path('novedades/', include('novedades.urls', namespace="novedades")),
    path('tablas/', include('tablas.urls', namespace="tablas")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

facturas/urls.py
from django.urls import path
from facturas.views import (
    FacturasListView, CreateFacturaView, FacturaDetailView,
    UpdateFacturaView, RemoveFacturaView, ResultadosListView,
    GetFacturasView)

app_name = 'facturas'

urlpatterns = [
    path('list/', FacturasListView.as_view(), name='list'),
    path('list/resultados', ResultadosListView.as_view(), name='resultados'),
    path('create/', CreateFacturaView.as_view(), name='add_factura'),
    path('<int:pk>/view/', FacturaDetailView.as_view(), name="view_factura"),
    path('<int:pk>/edit/', UpdateFacturaView.as_view(), name="edit_factura"),
    path('<int:pk>/delete/',
         RemoveFacturaView.as_view(),
         name="remove_factura"),

    path('get/list/', GetFacturasView.as_view(), name="get_facturas"),

]

contacts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from common.models import Address, User
from phonenumber_field.modelfields import PhoneNumberField


class Contact(models.Model):
    first_name = models.CharField(_("Nombre"), max_length=255)
    last_name = models.CharField(_("Apellido"), max_length=255)
    email = models.EmailField(unique=True)
    phone = PhoneNumberField(null=True, unique=True)
    address = models.ForeignKey(
        Address, related_name='adress_contacts',
        on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(
        User, related_name='contact_created_by',
        on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name

    class Meta:
        ordering = ['-created_on']

facturas/models.py
from django.db import models
from common.models import User
from django.utils.translation import ugettext_lazy as _

class IVA(models.Model):
    IVA_CHOICES = (('compras','Compras'),('ventas', 'Ventas'))

    tipo_iva = models.CharField(max_length=20, choices=IVA_CHOICES, default='ventas')

    periodo = models.DateField()
    neto_gravado = models.DecimalField(decimal_places=2, max_digits=10)
    neto_no_gravado = models.DecimalField(decimal_places=2, max_digits=10)
    exento = models.DecimalField(decimal_places=2, max_digits=10)
    iva = models.DecimalField(decimal_places=2, max_digits=10)
    percepcion = models.DecimalField(decimal_places=2, max_digits=10)
    total = models.DecimalField(decimal_places=2, max_digits=10)

    created_by = models.ForeignKey(
        User, related_name='factura_created_by',
        on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(_("Creado el"), auto_now_add=True)

    @property
    def total(self):
        return int(self.neto_gravado + self.neto_no_gravado + self.exento + self.iva + self.percepcion)

    def __str__(self):
        return "Tipo: {} {:%m-%Y}".format(self.tipo_iva.capitalize(),self.periodo)

common/forms.py
import re
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm
from common.models import (Address, User, Document, Comment, APISettings,
                            Empresa, Impuesto)

class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ('street', 'address_line', 'city',
                  'state', 'postcode', 'country')

    def __init__(self, *args, **kwargs):
        account_view = kwargs.pop('account', False)

        super(AddressForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['street'].widget.attrs.update({
            'placeholder': 'Calle'})
        self.fields['address_line'].widget.attrs.update({
            'placeholder': 'Número'})
        self.fields['city'].widget.attrs.update({
            'placeholder': 'Ciudad'})
        self.fields['state'].widget.attrs.update({
            'placeholder': 'Provincia'})
        self.fields['postcode'].widget.attrs.update({
            'placeholder': 'Código Postal'})
        self.fields["country"].choices = [
            ("", "--País--"), ] + list(self.fields["country"].choices)[1:]

        if account_view:
            self.fields['address_line'].required = True
            self.fields['street'].required = True
            self.fields['city'].required = True
            self.fields['state'].required = True
            self.fields['postcode'].required = True
            self.fields['country'].required = True


class UserForm(forms.ModelForm):

    password = forms.CharField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name',
                  'username', 'role', 'profile_pic']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].required = True
        if not self.instance.pk:
            self.fields['password'].required = True

        # self.fields['password'].required = True

    # def __init__(self, args: object, kwargs: object) -> object:
    #     super(UserForm, self).__init__(*args, **kwargs)
    #
    #     self.fields['first_name'].required = True
    #     self.fields['username'].required = True
    #     self.fields['email'].required = True
    #
        # if not self.instance.pk:
        #     self.fields['password'].required = True

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 4:
                raise forms.ValidationError(
                    'La contraseña debe tener al menos 4 caracteres!')
        return password

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.instance.id:
            if self.instance.email != email:
                if not User.objects.filter(
                        email=self.cleaned_data.get("email")).exists():
                    return self.cleaned_data.get("email")
                raise forms.ValidationError('Email already exists')
            else:
                return self.cleaned_data.get("email")
        else:
            if not User.objects.filter(
                    email=self.cleaned_data.get("email")).exists():
                return self.cleaned_data.get("email")
            raise forms.ValidationError('User already exists with this email')

class EmpresaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        asignado_impuestos = kwargs.pop('asignado_a', [])
        super(EmpresaForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['descripcion'].widget.attrs.update({
            'rows': '6'})
        self.fields['asignado_a'].queryset = asignado_impuestos
        self.fields['asignado_a'].required = False


        for key, value in self.fields.items():
            if key == 'telefono':
                value.widget.attrs['placeholder'] = "+54-351-456-7890"
            elif key == 'descripcion':
                value.widget.attrs['placeholder'] = "Descripción"
            else:
                value.widget.attrs['placeholder'] = value.label

    class Meta:
        model = Empresa
        fields = ['nombre', 'CUIT', 'DGR', 'mail', 'telefono', 'direccion', 'descripcion', 'asignado_a']

class ImpuestoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ImpuestoForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['descripcion'].widget.attrs.update({
            'rows': '6'})

        for key, value in self.fields.items():
            if key == 'descripcion':
                value.widget.attrs['placeholder'] = "Descripción"
            else:
                value.widget.attrs['placeholder'] = value.label

    class Meta:
        model = Impuesto
        fields = ['nombre', 'tipo', 'periodicidad', 'div_venc', 'pri_dia', 'descripcion']


class LoginForm(forms.ModelForm):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            if len(password) < 4:
                raise forms.ValidationError(
                    'La contraseña debe tener al menos 4 caracteres!')
        return password

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            self.user = authenticate(username=email, password=password)
            if self.user:
                if not self.user.is_active:
                    pass
                    # raise forms.ValidationError("User is Inactive")
            else:
                pass
                # raise forms.ValidationError("Invalid email and password")
        return self.cleaned_data


class ChangePasswordForm(forms.Form):
    CurrentPassword = forms.CharField(max_length=100)
    Newpassword = forms.CharField(max_length=100)
    confirm = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean_confirm(self):
        if len(self.data.get('confirm')) < 4:
            raise forms.ValidationError(
                'La contraseña debe tener al menos 4 caracteres!')
        if self.data.get('confirm') != self.cleaned_data.get('Newpassword'):
            raise forms.ValidationError(
                'Confirme que la contraseña sea diferente')
        return self.data.get('confirm')


class PasswordResetEmailForm(PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email__iexact=email,
                                   is_active=True).exists():
            raise forms.ValidationError("No hay un usuario con este email")
        return email


class DocumentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        users = kwargs.pop('users', [])
        super(DocumentForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}

        self.fields['status'].choices = [
            (each[0], each[1]) for each in Document.DOCUMENT_STATUS_CHOICE]
        self.fields['status'].required = False
        self.fields['title'].required = True
        self.fields['shared_to'].queryset = users
        self.fields['shared_to'].required = False

    class Meta:
        model = Document
        fields = ['title', 'document_file', 'status', 'shared_to']


class UserCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'user', 'commented_by')


def find_urls(string):
    # website_regex = "^((http|https)://)?([A-Za-z0-9.-]+\.[A-Za-z]{2,63})?$"  # (http(s)://)google.com or google.com
    # website_regex = "^https?://([A-Za-z0-9.-]+\.[A-Za-z]{2,63})?$"  # (http(s)://)google.com
    # http(s)://google.com
    website_regex = "^https?://[A-Za-z0-9.-]+\.[A-Za-z]{2,63}$"
    # http(s)://google.com:8000
    website_regex_port = "^https?://[A-Za-z0-9.-]+\.[A-Za-z]{2,63}:[0-9]{2,4}$"
    url = re.findall(website_regex, string)
    url_port = re.findall(website_regex_port, string)
    if url and url[0] != '':
        return url
    return url_port


class APISettingsForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(APISettingsForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}

        # self.fields['title'].widget.attrs.update({
        #     'placeholder': 'Project Name'})
        # self.fields['lead_assigned_to'].widget.attrs.update({
        #     'placeholder': 'Assign Leads To'})

    class Meta:
        model = APISettings
        fields = ('title', 'website')

    def clean_website(self):
        website = self.data.get('website')
        if website and not (website.startswith('http://') or
                            website.startswith('https://')):
            raise forms.ValidationError("Please provide valid schema")

facturas/forms.py
from django import forms

from .models import IVA

class FacturasForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(FacturasForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}

    class Meta:
        model = IVA
        fields = (
            'tipo_iva', 'periodo', 'neto_gravado',
            'neto_no_gravado', 'exento',
            'iva', 'percepcion'
        )

facturas/templates/create_factura.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
{% block extralinks %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'facturas:list' %}">Facturas</a></li>
    <li class="breadcrumb-item active">{% if factura_obj %}Editar{% else %}Crear{% endif %}</li>
  </ol>
</nav>
{% endblock %}
{% block content %}
<form id="add_form" method="POST" action='' novalidate enctype="multipart/form-data">
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-9">
      <div class="card">
        <div class="card-body">
          <div class="card-title text-center">
            {% if factura_obj %}EDITAR{% else %}CREAR{% endif %} FACTURA
          </div>
          <div class="row marl no-gutters justify-content-center">
            <div class="col-md-4">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <div class="row">
                    <div class="filter_col col-md-6">
                      <label for="exampleInputEmail1" class="required">Tipo Factura{% if factura_form.tipo_iva.field.required %}<span class="error">*</span>{% endif %}</label>
                      {{ factura_form.tipo_iva }}
                      <span class="error">{{ factura_form.tipo_iva.errors }}</span>
                    </div>
                    <div class="filter_col col-md-6">
                      <label for="exampleInputEmail1" class="required">Período{% if factura_form.periodo.field.required %}<span class="error">*</span>{% endif %}</label>
                      {{ factura_form.periodo }}
                      <span class="error">{{ factura_form.periodo.errors }}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group ">
                  <label for="exampleInputEmail1" class="required" >Neto Gravado{% if factura_form.neto_gravado.field.required %}<span class="error">*</span>{% endif %}</label>
                  {{ factura_form.neto_gravado }}
                  <span class="error">{{ factura_form.neto_gravado.errors }}</span>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group ">
                  <label for="exampleInputEmail1" class="required" >Neto no Gravado{% if factura_form.neto_no_gravado.field.required %}<span class="error">*</span>{% endif %}</label>
                  {{ factura_form.neto_no_gravado }}
                  <span class="error">{{ factura_form.neto_no_gravado.errors }}</span>
                </div>
              </div>
            </div>
          


            <div class="col-md-4">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Exento</label>
                  {{ factura_form.exento }}
                  <span class="error">{{ factura_form.exento.errors }}</span>
                </div>
              </div>

                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Iva</label>
                    {{ factura_form.iva }}
                    <span class="error">{{ factura_form.iva.errors }}</span>
                  </div>
                </div>


                  <div class="filter_col col-md-12">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Percepción</label>
                      {{ factura_form.percepcion }}
                      <span class="error">{{ factura_form.percepcion.errors }}</span>
                    </div>
                  </div>



                <br>
              </div>
            </div>

            <input type="hidden" id="save_new_form" name="savenewform">
            <div class="col-md-12">
              <div class="row marl buttons_row text-center form_btn_row">
                <button  class="btn btn-default save" type="submit">Grabar</button>
                {% if not factura_obj %}
                <button class="btn btn-success save savenew" type="submit">Grabar & Nuevo</button>
                {% endif %}
                <a href="{% url 'facturas:list' %}" class="btn btn-default clear" id="create_factura_cancel">Cancelar</a>
              </div>
            </div>
          </div>
        </div>

    </div>
  </div>
</form>
{% endblock %}
{% block js_block %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script type="text/javascript">
  $(".savenew").on('click', function(e){
    e.preventDefault()
    $("#save_new_form").val('true')
    $('#add_form').submit()
  });
  $(document).ready(function() {
    $('.assigned_users').select2();
  });
</script>
{% endblock js_block %}

facturas/templates/facturas.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% load paginate %}
{% load thumbnail %}
{% block extralinks %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- heading_create starts here -->
  <div class="row marl">
    <div class="col-lg-12 text-right">
      <span class="d-inline"><a class="primary_btn"  href="{% url 'facturas:add_factura'%}"><i class="fa fa-plus"></i> Agregar nueva factura</a></span>
      <span class="d-inline"><a class="secondary_btn"  href="#"><i class="fa fas fa-chart-bar"></i> Ver Resultados</a></span>
    </div>
  </div>
  <div class="filter_row list_filter_row row marl">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <form id="facturas_filter" action="" method="POST">
            <div class="card-body">
              <div class="card-title">Filtros</div>
              <div class="row marl">
                <div class="filter_col col-md-3">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Tipo de Factura</label>
                    <input type="text" class="form-control" placeholder="Tipo de Factura" name="tipo_iva" value="{{request.POST.tipo_iva}}">
                  </div>
                </div>
                <div class="filter_col col-md-3">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Período</label>
                    <input type="text" class="form-control" placeholder="Período" name="periodo" value="{{periodo}}">
                  </div>
                </div>

                <div class="filter_col text-center col-3">
                  <div class="form-group buttons_row">
                    <button  class="btn btn-primary save" type="submit">Buscar</button>
                    <a href="{% url 'facturas:list' %}" class="btn btn-default clear">Limpiar</a>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- heading_create ends here -->
  <!-- filter_row starts here -->
  <div class="table_container_row row marl ">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="card-title text-right">

             <span class="float-left">Facturas - {% if show_pageitems %} {% show_pageitems %}{% else %} {{facturas_obj_list|length}}{% endif %}</span>

              <span class="filter_toggle">
                <a href="#" class="primary_btn"><i class="fas fa-filter"></i></a>
              </span>

          </div>
          <div class="table-responsive">
            <table class="table">
              <thead>
                {% if facturas_obj_list|length > 0 %}
                <tr>
                  <th width="10%" >Tipo</th>
                  <th width="10%" >Período</th>
                  <th width="13%" >Neto Gravado</th>
                  <th width="10%" >Neto no Gravado</th>
                  <th width="10%" >Exento</th>
                  <th width="12%" >IVA</th>
                  <th width="10%" >Percepciones</th>
                  <th width="13%" >Total</th>
                  <th width="12%" >Acciones</th>
                </tr>
                {% endif %}
              </thead>
              <tbody>
                {% if per_page %}
                {% paginate per_page facturas_obj_list %}
                {% else%}
                {% paginate 10 facturas_obj_list %}
                {% endif %}
                {% for factura in facturas_obj_list %}
                <tr style="text-align:center;">
                  <td><a href="{% url 'facturas:view_factura' factura.id %}">{{factura.tipo_iva}}</a></td>
                  <td><a href="{% url 'facturas:view_factura' factura.id %}">{{factura.periodo}}</a></td>
                  <td>{{factura.neto_gravado}}</td>
                  <td>{{factura.neto_no_gravado}}</td>
                  <td>{{factura.exento}}</td>
                  <td>{{factura.iva}}</td>
                  <td>{{factura.percepcion}}</td>
                  <td>{{factura.total}}</td>
                  <td class="actions">
                    {#  <a href="{% url 'facturas:view_factura' factura.id %}" class="btn btn-info view"><i class="fas fa-eye"></i> Ver</a> #}
                    <a href="{% url 'facturas:edit_factura' factura.id%}" class="btn btn-success edit"><i class="fas fa-pencil-alt"></i></a>
                    {% if request.user == factura.created_by or request.user.role == "ADMIN" or request.user.is_superuser %}
                    <a href="{% url 'facturas:remove_factura' factura.id %}" class="btn btn-danger delete remove_account"><i class="fas fa-trash-alt"></i></a>
                    {% endif %}
                  </td>
                </tr>
                {% endfor%}
              </tbody>
            </table>
          </div>
          {%ifequal facturas_obj_list|length 0 %}
          <h6 class="text-center">No hay registros de facturas</h6>
          {%endifequal%}
          <div class="marl row text-center">
            {% show_pages %}
          </div>
        </div>
      </div>
    </div>
    <br clear="all">
  </div>
  <!-- filter_row ends here -->
</div>
<!-- main_container ends here -->
{%endblock%}
{% block js_block %}
<script type="text/javascript">
  $(document).ready(function(){
     $('.assigned_users').select2();
    $(".filter_toggle").click(function(){
      $(".list_filter_row").toggle();
    });
  });

  search = "{{search}}"

  if (search == 'True'){
    $(".list_filter_row").show();
  }
  $('.delete').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('¿Está seguro que desea borrar?'))
      return;
    window.location = $(this).attr('href')
  });

  $("a[rel='page']").click(function(e){
    e.preventDefault();
    $('#facturas_filter').attr("action", $(this).attr("href"));
    $('#facturas_filter').submit();
  });
</script>
{% endblock js_block %}

facturas/templates/facturas_list.html
<table class="table">
  <thead>
    <tr>
      <th width="50%">
        <a href='#'>
        Name
        </a>
        <span class="caret"></span>
      </th>
      <th>
        <a href="#">
        Email
        </a>
      </th>
    </tr>
  </thead>
  <tbody>
    {% ifequal facturas|length  0 %}
    <tr>
      <td class="cell">
        No hay facturas registradas!
      </td>
    </tr>
    {% endifequal %}
    {% for factura in facturas %}
    <tr>
      <td class="cell">
        <a class="cell parentname" id="{{ factura.id }}">
        {{ factura.tipo_iva }}
        </a>
      </td>
      <td class="cell parentemail">
        {{ factura.periodo }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

facturas/templates/view_factura.html
{% extends 'sales/base.html' %}
{% load staticfiles %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
  <li class="breadcrumb-item"> <a  href="{% url 'facturas:list' %}">Facturas</a></li>
  <li class="breadcrumb-item active">Ver</li>
</ol>
</nav>
{% endblock %}
{% block content %}
<!-- FACTURAS VIEW STARTS -->
  <div class="main_container" id="maincontainer">
    <div class="overview_form_block row marl justify-content-center">
      <div class="col-md-8">
        <div class="card">

          <div class="card-body" id="datashow">

           <div class="card-title text-right">
            <h5>
              <span class="float-left title">Resumen</span>
              <span class="" style="margin-top: 0px">
                <div class="dropdown buttons_row">
                  <button class="btn primary_btn dropdown-toggle" type="button" data-toggle="dropdown">Acciones
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'facturas:edit_factura' factura_record.id %}">Editar</a></li>
                  </ul>
                </div>
              </span>
            </h5>
          </div>

            <div class="row marl">
              <div class="col-md-4">
                <div class="filter_col col-md-12" id="iname">
                  <div class="form-group" >
                    <label class="factura_field_label" for="id_name" data-name="name">Período</label>
                    <div class="factura_field" id="factura_name" data-name="name">{{ factura_record.periodo }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="factura_field_label" for="id_phone" data-name="name">Neto Gravado</label>
                    <div class="factura_field" id="factura_phone" data-name="name">{{ factura_record.neto_gravado }}</div>
                  </div>
                </div>

              </div>
              <div class="col-md-4">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="factura_field_label" for="id_email" data-name="name">Neto no Gravado</label>
                    <div class="factura_field" id="factura_email" data-name="name">{{ factura_record.neto_no_gravado }}</div>
                  </div>
                </div>

                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="factura_field_label" for="id_email" data-name="name">Exento</label>
                    <div class="factura_field" id="factura_email" data-name="name">{{ factura_record.exento }}</div>
                  </div>
                </div>

              </div>
              <div class="col-md-4">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="factura_field_label" for="id_address" data-name="name" >IVA</label>
                    <div class="factura_field" id="factura_address" data-name="name">{{ factura_record.iva }}</div>
                    </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="factura_field_label" for="id_description" data-name="name">Percepción</label>
                    <div class="factura_field" id="factura_description" data-name="name">{{ factura_record.percepcion }}</div>
                    </div>
                </div>
              </div>
              <div class="col-md-12">
                <div class="created_information">
                  Total Factura <b>{{ factura_record.total }}</b>
                </div>
              </div>
            </div>
          </div>

{% endblock%}