common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin,
    EmpresasListView, EmpresaDetailView, CreateEmpresaView, UpdateEmpresaView,
    EmpresaDeleteView, change_empresa_status,
    ImpuestosListView, ImpuestoDetailView, CreateImpuestoView, UpdateImpuestoView,
    ImpuestoDeleteView, change_empresa_status
)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'common'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    # Empresas views
    path('empresas/list/', EmpresasListView.as_view(), name='empresas_list'),
    path('empresas/create/', CreateEmpresaView.as_view(), name='create_empresa'),
    path('empresas/<int:pk>/edit/', UpdateEmpresaView.as_view(), name="edit_empresa"),
    path('empresas/<int:pk>/view/', EmpresaDetailView.as_view(), name='view_empresa'),
    path('empresas/<int:pk>/delete/', EmpresaDeleteView.as_view(), name='remove_empresa'),

    # Impuestos views
    path('impuestos/list/', ImpuestosListView.as_view(), name='impuestos_list'),
    path('impuestos/create/', CreateImpuestoView.as_view(), name='create_impuesto'),
    path('impuestos/<int:pk>/edit/', UpdateImpuestoView.as_view(), name="edit_impuesto"),
    path('impuestos/<int:pk>/view/', ImpuestoDetailView.as_view(), name='view_impuesto'),
    path('impuestos/<int:pk>/delete/', ImpuestoDeleteView.as_view(), name='remove_impuesto'),


    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/list/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),
    path('empresa/status/<int:pk>/',
         change_empresa_status, name='change_empresa_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('facturas/', include('facturas.urls', namespace="facturas")),
    path('novedades/', include('novedades.urls', namespace="novedades")),
    path('tablas/', include('tablas.urls', namespace="tablas")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

common/models.py
import binascii
import os
import time
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
                                        UserManager)
from common.templatetags.common_tags import (
    is_document_file_image, is_document_file_audio,
    is_document_file_video, is_document_file_pdf,
    is_document_file_code, is_document_file_text,
    is_document_file_sheet, is_document_file_zip
)
from common.utils import COUNTRIES, ROLES


def img_url(self, filename):
    hash_ = int(time.time())
    return "%s/%s/%s" % ("profile_pics", hash_, filename)

class User(AbstractBaseUser, PermissionsMixin):
    file_prepend = "users/profile_pics"
    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True)
    role = models.CharField(max_length=50, choices=ROLES)
    profile_pic = models.FileField(
        max_length=1000, upload_to=img_url, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def documents(self):
        return self.document_uploaded.all()

    def get_full_name(self):
        full_name = None
        if self.first_name or self.last_name:
            full_name = self.first_name + " " + self.last_name
        elif self.username:
            full_name = self.username
        else:
            full_name = self.email
        return full_name

    def __str__(self):
        return self.email

    class Meta:
        ordering = ['-is_active']


class Address(models.Model):
    street = models.CharField(
        _("Calle"), max_length=55, blank=True, null=True)
    address_line = models.CharField(
        _("Número"), max_length=255, blank=True, null=True)
    city = models.CharField(_("Ciudad"), max_length=255, blank=True, null=True)
    state = models.CharField(_("Provincia"), max_length=255, blank=True, null=True)
    postcode = models.CharField(
        _("Código Postal"), max_length=64, blank=True, null=True)
    country = models.CharField(_("País"),
        max_length=3, choices=COUNTRIES, blank=True, null=True)

    def __str__(self):
        return self.city if self.city else ""

    def get_complete_address(self):
        address = ""
        if self.street:
            address += self.street
        if self.address_line:
            if address:
                address += " " + self.address_line
            else:
                address += self.address_line
        if self.city:
            if address:
                address += ", " + self.city
            else:
                address += self.city
        if self.state:
            if address:
                address += ", " + self.state
            else:
                address += self.state
        if self.postcode:
            if address:
                address += ", " + self.postcode
            else:
                address += self.postcode
        if self.country:
            if address:
                address += ", " + self.get_country_display()
            else:
                address += self.get_country_display()
        return address

class Impuesto(models.Model):
    Tipo_Choices = (('nacional','Nacional'),('provincial', 'Provincial'),('municipal', 'Municipal'))
    Tipo_Periodicidad = (('mensual','Mensual'),('anual', 'Anual'),('trimestral', 'Trimestral'))

    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=20, choices=Tipo_Choices, default='nacional')
    periodicidad = models.CharField(max_length=20, choices=Tipo_Periodicidad, default='mensual')
    div_venc = models.IntegerField()
    pri_dia= models.IntegerField(default=0)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['nombre']

class Vencimiento(models.Model):
    Term_Choices = [(i,i) for i in range(10)]

    impuesto = models.ForeignKey(
        Impuesto, related_name='impuesto_vencimiento',
        on_delete=models.CASCADE)

    periodo = models.DateField(auto_now=False, auto_now_add=False)
    terminacion = models.IntegerField(choices=Term_Choices) #funciona como un desde
    vencimiento = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return '%s %s %s' % (self.impuesto, "-", self.terminacion)

    class Meta:
        ordering = ['vencimiento']

class Empresa(models.Model):
    nombre = models.CharField(max_length=50, unique = True)
    CUIT = models.BigIntegerField()
    DGR = models.BigIntegerField(default=0, null=True)
    is_active = models.BooleanField(default=True)
    mail = models.CharField(max_length=50)
    telefono = models.CharField(max_length=50)
    direccion = models.ForeignKey(
        Address, related_name='direccion_empresa',
        on_delete=models.CASCADE, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    asignado_a = models.ManyToManyField(Impuesto, related_name='empresa_impuesto')

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['-is_active', 'nombre']


class Comment(models.Model):
    comment = models.CharField(max_length=255)
    commented_on = models.DateTimeField(auto_now_add=True)
    commented_by = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    contact = models.ForeignKey(
        'contacts.Contact', blank=True,
        null=True, related_name="contact_comments",
        on_delete=models.CASCADE)
    user = models.ForeignKey(
        'User', blank=True, null=True,
        related_name="user_comments",
        on_delete=models.CASCADE)

    def get_files(self):
        return Comment_Files.objects.filter(comment_id=self)


class Comment_Files(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now_add=True)
    comment_file = models.FileField(
        "File", upload_to="comment_files", default='')

    def get_file_name(self):
        if self.comment_file:
            return self.comment_file.path.split('/')[-1]

        return None


class Attachments(models.Model):
    created_by = models.ForeignKey(
        User, related_name='attachment_created_by',
        on_delete=models.SET_NULL, null=True)
    file_name = models.CharField(max_length=60)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    attachment = models.FileField(
        max_length=1001, upload_to='attachments/%Y/%m/')
    contact = models.ForeignKey(
        'contacts.Contact', on_delete=models.CASCADE,
        related_name='contact_attachment',
        blank=True, null=True)

    def file_type(self):
        name_ext_list = self.attachment.url.split(".")
        if (len(name_ext_list) > 1):
            ext = name_ext_list[int(len(name_ext_list) - 1)]
            if is_document_file_audio(ext):
                return ("audio", "fa fa-file-audio")
            if is_document_file_video(ext):
                return ("video", "fa fa-file-video")
            if is_document_file_image(ext):
                return ("image", "fa fa-file-image")
            if is_document_file_pdf(ext):
                return ("pdf", "fa fa-file-pdf")
            if is_document_file_code(ext):
                return ("code", "fa fa-file-code")
            if is_document_file_text(ext):
                return ("text", "fa fa-file-alt")
            if is_document_file_sheet(ext):
                return ("sheet", "fa fa-file-excel")
            if is_document_file_zip(ext):
                return ("zip", "fa fa-file-archive")
            return ("file", "fa fa-file")
        return ("file", "fa fa-file")

    def get_file_type_display(self):
        if self.attachment:
            return self.file_type()[1]
        return None


def document_path(self, filename):
    hash_ = int(time.time())
    return "%s/%s/%s" % ("docs", hash_, filename)


class Document(models.Model):

    DOCUMENT_STATUS_CHOICE = (
        ("activo", "activo"),
        ('inactivo', 'inactivo')
    )

    title = models.CharField(max_length=1000, blank=True, null=True)
    document_file = models.FileField(upload_to=document_path, max_length=5000)
    created_by = models.ForeignKey(
        User, related_name='document_uploaded',
        on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        choices=DOCUMENT_STATUS_CHOICE, max_length=64, default='activo')
    shared_to = models.ManyToManyField(User, related_name='document_shared_to')

    def file_type(self):
        name_ext_list = self.document_file.url.split(".")
        if (len(name_ext_list) > 1):
            ext = name_ext_list[int(len(name_ext_list) - 1)]
            if is_document_file_audio(ext):
                return ("audio", "fa fa-file-audio")
            if is_document_file_video(ext):
                return ("video", "fa fa-file-video")
            if is_document_file_image(ext):
                return ("image", "fa fa-file-image")
            if is_document_file_pdf(ext):
                return ("pdf", "fa fa-file-pdf")
            if is_document_file_code(ext):
                return ("code", "fa fa-file-code")

common/templates/settings/list.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- filter_row starts here -->
  <div class="row marl">
    <div class="col-lg-12 text-right">
      <span class="d-inline"><a href="{% url 'common:add_api_settings'%}" class="btn primary_btn"><i class="fa fa-plus"></i> Add New Setting</a></span>
    </div>
  </div>
  <!-- filter_row ends here -->
  <div class="table_container_row row marl">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="card-title list text-right">
            <span class="float-left">Settings - {% if show_pageitems %} {% show_pageitems %}{% else %} {{ settings|length }}{% endif %}</span>
            <span class="filter_toggle">
            <a style="padding:0px 10px " href="#" class="primary_btn"></a>
            </span>
          </div>
          <div class="table-responsive ">
            <table class="table table-bordered table-striped table-condensed">
              <thead>
                {% if settings|length > 0 %}
                <tr>
                  <th width="20%">Title</th>
                  <!-- <th width="20%">API Key</th> -->
                  <th width="30%">Assign To</th>
                  <th width="15%">User</th>
                  <th width="10%">Actions</th>
                </tr>
                {% endif %}
              </thead>
              <tbody>
                {% if per_page %}
                {% paginate per_page settings %}
                {% else %}
                {% paginate 10 settings %}
                {% endif %}
                {% for setting in settings %}
                <tr class="text-center">
                  <td><a href="{% url 'common:view_api_settings' setting.id %}">{{ setting.title }}</a></td>
                  <!-- <td>{{ setting.apikey }}</td> -->
                  <td>
                  	{% for user in setting.lead_assigned_to.all %}
                  		{{user.email}}{% if forloop.counter < setting.lead_assigned_to.all|length %}, {% endif %}
                  	{% empty %}
                  		Not Assigned Yet!
              			{% endfor %}
              		</td>
                  <td>{% if setting.created_by %}{{ setting.created_by.email }}{% else %}No user!{% endif %}</td>
                  <td class="actions">
                    <!-- <a href="{% url 'common:view_api_settings' setting.id %}" class="btn btn-info view"><i class="fas fa-eye"></i>View</a> -->
                    <a href="{% url 'common:update_api_settings' setting.id %}" class="btn btn-success edit action"><i class="fas fa-pencil-alt"></i>Edit</a>
                    <a href="{% url 'common:delete_api_settings' setting.id %}" class="btn btn-danger trash action"><i class="fas fa-trash-alt"></i>Delete</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% ifequal settings|length 0 %}
          <h6 class="text-center">No Settings Found!</h6>
          {% endifequal %}
          <div class="marl row text-center">
            {% show_pages %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- main_container ends here -->
{% endblock %}
{% block js_block %}
<script type="text/javascript">
  $('.trash').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });
</script>
{% endblock js_block %}


common/templates/settings/update.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% block extralinks %}
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="http://xoxco.com/examples/jquery.tagsinput.css" />

  <link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/start/jquery-ui.css" />
{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'common:api_settings' %}">Settings</a></li>
    <li class="breadcrumb-item"><a href="{% url 'common:view_api_settings' setting.id %}">{{ setting.title }}</a></li>
    <li class="breadcrumb-item active">Edit</li>
  </ol>
</nav>
{% endblock %}
{%block content%}
<form id="update_form" method="POST" action="" novalidate>
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-9">
      <div class="card">
        <div class="card-body">
          <div class="card-title text-center">
            EDIT SETTINGS
          </div>
          <div class="row marl no-gutters">
            <div class="col-md-12">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label>Title{% if settings_form.title.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="text" name="title" class="form-control" value="{% if setting %}{{setting.title}}{% endif %}">
                  <span class="error">{{ settings_form.title.errors }}</span>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label>Website{% if settings_form.website.field.required %}<span class="error">*</span>{% endif %} <span class="help-text">Example: http://google.com</span></label>
                  <input type="text" name="website" class="form-control" value="{% if setting %}{{setting.website}}{% endif %}">
                  <span class="error">{{ settings_form.website.errors }}</span>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label>Assigned Users</label>
                  <select class="assigned_users form-control" name="lead_assigned_to" multiple="multiple">
                    {% for user in users %}
                      <option value="{{user.id}}" {% if user in setting.lead_assigned_to.all or user.id in assign_to_list %}selected{% endif %}>{{user.email}}</option>
                    {% endfor %}
                  </select>
                  <span class="error">{{ settings_form.lead_assigned_to.errors }}</span>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="filter_col col-12">
                <div class="form-group">
                  <label>Tags</label>
                  <div class="txt-box-div" id="tag-div"><input type="text" name="tags" id="tags_1" value="{% for t in setting.tags.all %}{{t.name}}, {% endfor %}" class="tags"/>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="row marl buttons_row text-center form_btn_row">
                <button  class="btn btn-default save" type="submit">Save</button>
                {% if not setting %}
                <button class="btn btn-success save savenew" type="submit">Save & New</button>
                {% endif %}
                <a href="{% url 'common:api_settings' %}" class="btn btn-default clear" id="create_lead_cancel">Cancel</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <input type="hidden" id="save_new_form" name="savenewform">
  </div>
</form>
{% endblock %}
{% block js_block %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.js"></script>
  <script type="text/javascript">
    $("#update_form").submit(function(e){
      e.preventDefault();
      $form = $(this)
      $.post("", $form.serialize(), function(response){
         $(".error_message").remove();
          if(response.error){
            $.each(response.errors, function(field_name, error){
              if (field_name == '__all__'){
                error = "<span class=\"error_message\" style=color:red>" + error + "</span>"
                $("span.__all__").after(error)
              }else{
                error = "<span class=\"error_message\" style=color:red>" + error + "</span>"
                $form.find("[name="+field_name + "]").after(error)
              }
            })
          }
         else{
          window.location = response.success_url
         }
      });
    });
    $(".savenew").on('click', function(e){
      e.preventDefault()
      $("#save_new_form").val('true')
      $('#update_form').submit()
    });
    $(document).ready(function() {
      var selected_users = "{{assigned_to_list}}";
      selected_users = JSON.parse(selected_users.replace(/&(l|g|quo)t;/g, function(a,b){
           return {
               l   : '<',
               g   : '>',
               quo : '"'
           }[b];
       }));
      var s2 = $(".assigned_users").select2({
          placeholder: "Choose Users to assign",
          tags: true
      });

      s2.val(selected_users).trigger("change");
    });
    $(function() {
      $('#tags_1').tagsInput({width:'auto'});
      $('#tags_2').tagsInput({
        width: 'auto',
        onChange: function(elem, elem_tags)
        {
          var languages = ['php','ruby','javascript'];
          $('.tag', elem_tags).each(function()
          {
            if($(this).text().search(new RegExp('\\b(' + languages.join('|') + ')\\b')) >= 0)
              $(this).css('background-color', 'yellow');
          });
        }
      });
      $('#tags_3').tagsInput({
        width: 'auto',
    
        //autocomplete_url:'test/fake_plaintext_endpoint.html' //jquery.autocomplete (not jquery ui)
        autocomplete_url:'test/fake_json_endpoint.html' // jquery ui autocomplete requires a json endpoint
      });


    // Uncomment this line to see the callback functions in action
    //      $('input.tags').tagsInput({onAddTag:onAddTag,onRemoveTag:onRemoveTag,onChange: onChangeTag});   

    // Uncomment this line to see an input with no interface for adding new tags.
    //      $('input.tags').tagsInput({interactive:false});
    });

  </script>
{% endblock js_block %}

common/templates/settings/view.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'common:api_settings' %}">Settings</a></li>
    <li class="breadcrumb-item active">{{ setting.title }} - View</li>
  </ol>
</nav>
{% endblock %}
{% block content %}
<div class="main_container" id="maincontainer">
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body" id="datashow">
          <div class="card-title text-right">
            <h5 >
              <span class="float-left title">Overview</span>
              <span class="" style="margin-top: 0px">
                <div class="dropdown buttons_row">
                  <button class="btn primary_btn dropdown-toggle " type="button" data-toggle="dropdown">Actions
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'common:update_api_settings' setting.id %}" >Edit</a></li>
                    <li class="trash"><a href="{% url 'common:delete_api_settings' setting.id %}" >Delete</a></li>
                  </ul>
                </div>
              </span>
            </h5>
          </div>
          <div class="row ">
            <div class="col-md-12">
              {% if setting.title %}
              <div class="filter_col col-md-12" id="iname">
                <div class="form-group" >
                  <label class="acc_field_label" for="id_name" data-name="name">Title</label>
                  <div class="account_field" id="account_name" data-name="name">{{ setting.title }}</div>
                </div>
              </div>
              {% endif %}
              {% if setting.website %}
              <div class="filter_col col-md-12" id="iname">
                <div class="form-group" >
                  <label class="acc_field_label" for="id_name" data-name="name">Website</label>
                  <div class="account_field" id="account_name" data-name="name">{{ setting.website }}</div>
                </div>
              </div>
              {% endif %}
              {% if setting.apikey %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="acc_field_label" for="id_phone" data-name="name">API KEY</label>
                  <div class="account_field" id="account_phone" data-name="name">
                    <span class="copy-text" id="texttocopy">{{ setting.apikey }}</span>
                    <span class="btn btn-primary" onclick="copyToClipboard('#texttocopy')"><i class="fa fa-copy"></i> Copy</span>
                  </div>
                </div>
              </div>
              {% endif %}
              {% if setting.created_by %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="acc_field_label" for="id_email" data-name="name">Created By</label>
                  <div class="account_field" id="account_email" data-name="name">{{ setting.created_by.email }}</div>
                </div>
              </div>
              {% endif %}
              {% if setting.created_on %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="acc_field_label" for="id_email" data-name="name">Created On</label>
                  <div class="account_field" id="account_email" data-name="name">{{ setting.created_on }}</div>
                </div>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block js_block %}
<script type="text/javascript">
  $('.trash').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });

  function copyToClipboard(element) {
    var $temp = $("<input>");
    $("body").append($temp);
    $temp.val($(element).html()).select();
    document.execCommand("copy");
    $temp.remove();
    alert("Copied!")
  }

</script>
{% endblock js_block %}