common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin,
    EmpresasListView, EmpresaDetailView, CreateEmpresaView, UpdateEmpresaView,
    EmpresaDeleteView, change_empresa_status,
    ImpuestosListView, ImpuestoDetailView, CreateImpuestoView, UpdateImpuestoView,
    ImpuestoDeleteView, change_empresa_status
)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'common'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    # Empresas views
    path('empresas/list/', EmpresasListView.as_view(), name='empresas_list'),
    path('empresas/create/', CreateEmpresaView.as_view(), name='create_empresa'),
    path('empresas/<int:pk>/edit/', UpdateEmpresaView.as_view(), name="edit_empresa"),
    path('empresas/<int:pk>/view/', EmpresaDetailView.as_view(), name='view_empresa'),
    path('empresas/<int:pk>/delete/', EmpresaDeleteView.as_view(), name='remove_empresa'),

    # Impuestos views
    path('impuestos/list/', ImpuestosListView.as_view(), name='impuestos_list'),
    path('impuestos/create/', CreateImpuestoView.as_view(), name='create_impuesto'),
    path('impuestos/<int:pk>/edit/', UpdateImpuestoView.as_view(), name="edit_impuesto"),
    path('impuestos/<int:pk>/view/', ImpuestoDetailView.as_view(), name='view_impuesto'),
    path('impuestos/<int:pk>/delete/', ImpuestoDeleteView.as_view(), name='remove_impuesto'),


    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/list/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),
    path('empresa/status/<int:pk>/',
         change_empresa_status, name='change_empresa_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('facturas/', include('facturas.urls', namespace="facturas")),
    path('novedades/', include('novedades.urls', namespace="novedades")),
    path('tablas/', include('tablas.urls', namespace="tablas")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

common/models.py
import binascii
import os
import time
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
                                        UserManager)
from common.templatetags.common_tags import (
    is_document_file_image, is_document_file_audio,
    is_document_file_video, is_document_file_pdf,
    is_document_file_code, is_document_file_text,
    is_document_file_sheet, is_document_file_zip
)
from common.utils import COUNTRIES, ROLES


def img_url(self, filename):
    hash_ = int(time.time())
    return "%s/%s/%s" % ("profile_pics", hash_, filename)

class User(AbstractBaseUser, PermissionsMixin):
    file_prepend = "users/profile_pics"
    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True)
    role = models.CharField(max_length=50, choices=ROLES)
    profile_pic = models.FileField(
        max_length=1000, upload_to=img_url, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def documents(self):
        return self.document_uploaded.all()

    def get_full_name(self):
        full_name = None
        if self.first_name or self.last_name:
            full_name = self.first_name + " " + self.last_name
        elif self.username:
            full_name = self.username
        else:
            full_name = self.email
        return full_name

    def __str__(self):
        return self.email

    class Meta:
        ordering = ['-is_active']


class Address(models.Model):
    street = models.CharField(
        _("Calle"), max_length=55, blank=True, null=True)
    address_line = models.CharField(
        _("Número"), max_length=255, blank=True, null=True)
    city = models.CharField(_("Ciudad"), max_length=255, blank=True, null=True)
    state = models.CharField(_("Provincia"), max_length=255, blank=True, null=True)
    postcode = models.CharField(
        _("Código Postal"), max_length=64, blank=True, null=True)
    country = models.CharField(_("País"),
        max_length=3, choices=COUNTRIES, blank=True, null=True)

    def __str__(self):
        return self.city if self.city else ""

    def get_complete_address(self):
        address = ""
        if self.street:
            address += self.street
        if self.address_line:
            if address:
                address += " " + self.address_line
            else:
                address += self.address_line
        if self.city:
            if address:
                address += ", " + self.city
            else:
                address += self.city
        if self.state:
            if address:
                address += ", " + self.state
            else:
                address += self.state
        if self.postcode:
            if address:
                address += ", " + self.postcode
            else:
                address += self.postcode
        if self.country:
            if address:
                address += ", " + self.get_country_display()
            else:
                address += self.get_country_display()
        return address

class Impuesto(models.Model):
    Tipo_Choices = (('nacional','Nacional'),('provincial', 'Provincial'),('municipal', 'Municipal'))
    Tipo_Periodicidad = (('mensual','Mensual'),('anual', 'Anual'),('trimestral', 'Trimestral'))

    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=20, choices=Tipo_Choices, default='nacional')
    periodicidad = models.CharField(max_length=20, choices=Tipo_Periodicidad, default='mensual')
    div_venc = models.IntegerField()
    pri_dia= models.IntegerField(default=0)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['nombre']

class Vencimiento(models.Model):
    Term_Choices = [(i,i) for i in range(10)]

    impuesto = models.ForeignKey(
        Impuesto, related_name='impuesto_vencimiento',
        on_delete=models.CASCADE)

    periodo = models.DateField(auto_now=False, auto_now_add=False)
    terminacion = models.IntegerField(choices=Term_Choices) #funciona como un desde
    vencimiento = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return '%s %s %s' % (self.impuesto, "-", self.terminacion)

    class Meta:
        ordering = ['vencimiento']

class Empresa(models.Model):
    nombre = models.CharField(max_length=50, unique = True)
    CUIT = models.BigIntegerField()
    DGR = models.BigIntegerField(default=0, null=True)
    is_active = models.BooleanField(default=True)
    mail = models.CharField(max_length=50)
    telefono = models.CharField(max_length=50)
    direccion = models.ForeignKey(
        Address, related_name='direccion_empresa',
        on_delete=models.CASCADE, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    asignado_a = models.ManyToManyField(Impuesto, related_name='empresa_impuesto')

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['-is_active', 'nombre']


class Comment(models.Model):
    comment = models.CharField(max_length=255)
    commented_on = models.DateTimeField(auto_now_add=True)
    commented_by = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    contact = models.ForeignKey(
        'contacts.Contact', blank=True,
        null=True, related_name="contact_comments",
        on_delete=models.CASCADE)
    user = models.ForeignKey(
        'User', blank=True, null=True,
        related_name="user_comments",
        on_delete=models.CASCADE)

    def get_files(self):
        return Comment_Files.objects.filter(comment_id=self)


class Comment_Files(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now_add=True)
    comment_file = models.FileField(
        "File", upload_to="comment_files", default='')

    def get_file_name(self):
        if self.comment_file:
            return self.comment_file.path.split('/')[-1]

        return None


class Attachments(models.Model):
    created_by = models.ForeignKey(
        User, related_name='attachment_created_by',
        on_delete=models.SET_NULL, null=True)
    file_name = models.CharField(max_length=60)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    attachment = models.FileField(
        max_length=1001, upload_to='attachments/%Y/%m/')
    contact = models.ForeignKey(
        'contacts.Contact', on_delete=models.CASCADE,
        related_name='contact_attachment',
        blank=True, null=True)

    def file_type(self):
        name_ext_list = self.attachment.url.split(".")
        if (len(name_ext_list) > 1):
            ext = name_ext_list[int(len(name_ext_list) - 1)]
            if is_document_file_audio(ext):
                return ("audio", "fa fa-file-audio")
            if is_document_file_video(ext):
                return ("video", "fa fa-file-video")
            if is_document_file_image(ext):
                return ("image", "fa fa-file-image")
            if is_document_file_pdf(ext):
                return ("pdf", "fa fa-file-pdf")
            if is_document_file_code(ext):
                return ("code", "fa fa-file-code")
            if is_document_file_text(ext):
                return ("text", "fa fa-file-alt")
            if is_document_file_sheet(ext):
                return ("sheet", "fa fa-file-excel")
            if is_document_file_zip(ext):
                return ("zip", "fa fa-file-archive")
            return ("file", "fa fa-file")
        return ("file", "fa fa-file")

    def get_file_type_display(self):
        if self.attachment:
            return self.file_type()[1]
        return None


def document_path(self, filename):
    hash_ = int(time.time())
    return "%s/%s/%s" % ("docs", hash_, filename)


class Document(models.Model):

    DOCUMENT_STATUS_CHOICE = (
        ("activo", "activo"),
        ('inactivo', 'inactivo')
    )

    title = models.CharField(max_length=1000, blank=True, null=True)
    document_file = models.FileField(upload_to=document_path, max_length=5000)
    created_by = models.ForeignKey(
        User, related_name='document_uploaded',
        on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        choices=DOCUMENT_STATUS_CHOICE, max_length=64, default='activo')
    shared_to = models.ManyToManyField(User, related_name='document_shared_to')

    def file_type(self):
        name_ext_list = self.document_file.url.split(".")
        if (len(name_ext_list) > 1):
            ext = name_ext_list[int(len(name_ext_list) - 1)]
            if is_document_file_audio(ext):
                return ("audio", "fa fa-file-audio")
            if is_document_file_video(ext):
                return ("video", "fa fa-file-video")
            if is_document_file_image(ext):
                return ("image", "fa fa-file-image")
            if is_document_file_pdf(ext):
                return ("pdf", "fa fa-file-pdf")
            if is_document_file_code(ext):
                return ("code", "fa fa-file-code")

contacts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from common.models import Address, User
from phonenumber_field.modelfields import PhoneNumberField


class Contact(models.Model):
    first_name = models.CharField(_("Nombre"), max_length=255)
    last_name = models.CharField(_("Apellido"), max_length=255)
    email = models.EmailField(unique=True)
    phone = PhoneNumberField(null=True, unique=True)
    address = models.ForeignKey(
        Address, related_name='adress_contacts',
        on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(
        User, related_name='contact_created_by',
        on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name

    class Meta:
        ordering = ['-created_on']

common/templates/create.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% if request.user != user_obj %}
    <li class="breadcrumb-item"><a href="{% url 'common:users_list' %}">Usuarios</a></li>
    <li class="breadcrumb-item">{% if user_obj %}Editar{% else %}Crear{% endif %}</li>
    {% endif %}
  </ol>
</nav>
{% endblock breadcrumb %}
{% block content %}
<form id="add_form" method="POST" action="" novalidate>
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-lg-7">
      <div class="card">
        <div class="card-body">
          <div class="card-title text-center">
            {% if user_obj %}EDITAR{% else %}CREAR{% endif %} USUARIO
          </div>
          <div class="row marl">
            <div class="filter_col col-md-4">
              <div class="form-group">
                <label for="id_firstname">Nombre{% if user_form.first_name.field.required %}<span class="error">*</span>{% endif %}</label>
                <input type="text" class="form-control" name="first_name" value="{% if user_obj %}{{ user_obj.first_name }}{% else %}{{request.POST.first_name}}{% endif %}" placeholder="Nombre">
              </div>
              <span class="error_ajax" id="id_first_name" style="color:red">{{ errors.first_name }}</span>
            </div>
            <div class="filter_col col-md-4">
              <div class="form-group">
                <label for="id_lastname">Apellido{% if user_form.last_name.field.required %}<span class="error">*</span>{% endif %}</label>
                <input type="text" class="form-control" name="last_name" value="{% if user_obj %}{{ user_obj.last_name }}{% else %}{{request.POST.last_name}}{% endif %}" placeholder="Apellido">
              </div>
              <span class="error_ajax" id="id_last_name" style="color:red">{{ errors.last_name }}</span>
            </div>
            <div class="filter_col col-md-4">
              <div class="form-group">
                <label for="id_username">Usuario{% if user_form.username.field.required %}<span class="error">*</span>{% endif %}</label>
                <input type="text" class="form-control" name="username" value="{% if user_obj %}{{ user_obj.username }}{% else %}{{request.POST.username}}{% endif %}" placeholder="Username">
              </div>
              <span class="error_ajax" id="id_username" style="color:red">{{ errors.username }}</span>
            </div>
            <div class="filter_col col-md-6" {% if user_obj %} style="display: none;" {% endif %}>
            <div class="form-group">
              <label for="id_email">Email{% if user_form.email.field.required %}<span class="error">*</span>{% endif %}</label>
              <input type="text" class="form-control" name="email" value="{% if user_obj %}{{ user_obj.email }}{% else %}{{request.POST.email}}{% endif %}" {% if user_obj %} readonly=""{% endif %} placeholder="Email">
            </div>
            <span class="error_ajax" id="id_email" style="color:red">{{ errors.email }}</span>
          </div>
          <div class="filter_col col-md-6" {% if request.user.role != 'ADMIN' and not request.user.is_superuser or request.user.id == user_obj.id %}style="display:none;"{% endif %}>
          <div class="form-group">
            <label for="id_role">Rol usuario{% if user_form.role.field.required %}<span class="error">*</span>{% endif %}</label>
            {% if request.user.role == 'ADMIN' or request.user.is_superuser %}
            <select name="role" class="form-control">
            {% for key, value in form.role.field.choices %}
            <option value="{{key}}" {% if value == user_obj.role %}selected="selected"{% elif user_obj.is_superuser and value == "ADMIN" %}selected{% endif %}>{{value}}</option>
            {% endfor %}
            </select>
            {% else %}
            <select name="role">
              <option value="{{user_obj.role}}">{{user_obj.role}}</option>
            </select>
            {% endif %}
            <span class="error_ajax" id="id_role" style="color:red">{{ user_form.role.errors }}</span>
          </div>
        </div>
        {% if not user_obj %}
        <div class="filter_col col-md-6">
          <div class="form-group">
            <label for="exampleInputEmail1">Contraseña{% if user_form.password.field.required %}<span class="error">*</span>{% endif %}</label>
            <input type="password" class="form-control" name="password" value="{{request.POST.password}}" placeholder="Password">
          </div>
          <span class="error_ajax" id="id_password" style="color:red">{{ errors.password }}</span>
        </div>
        {% endif %}
        <div class="filter_col col-md-6">
          <div class="form-group">
            <label for="exampleInputEmail1">Subir foto usuario{% if user_form.profile_pic.field.required %}<span class="error">*</span>{% endif %}</label>
            <input type="file" name="profile_pic" accept="image/*" class="form-control" />
          </div>

          {% if user_obj %}<span>{{user_profile_name }}</span>{% endif %}
          <span class="error" id="id_profile_pic">{{ errors.profile_pic }}</span>

        </div>
      </div>
    </div>
    <p style="color:red" id="forbiden_error"></p>
    <div class="row marl buttons_row form_btn_row text-center">
      <button class="btn btn-default save" type="submit">Grabar</button>
      <a href="{% if not user_obj or request.user.is_superuser or request.user.role == 'ADMIN' %}
        {% url 'common:users_list' %}
      {% else %}
        {% url 'common:profile' %}
      {% endif %}"
      class="btn btn-default clear" id="create_user_cancel">Cancelar</a>
    </div>
  </div>
  </div>
  </div>
</form>
{% endblock content %}
{% block js_block %}
<script src="https://malsup.github.io/jquery.form.js"></script>
<script type="text/javascript">
  $('form#add_form').ajaxForm({
     type:'POST',
     dataType:'json',
     url: ".",
     data:$('#add_form').serialize(),
     success: function(data) {
       if(data.error){
       if(data.error_403){
           $("#forbiden_error").text(" *No tienes permiso para editar este usuario");
         }
       if(data.errors){
         $('.error_ajax').html('')
         for (var key in data.errors) {
           $('#id_'+key).html("<p>" + data.errors[key][0] + "</p>");
         };
       }
       }
         else{
           window.location = data.success_url;
         }
     }
   });
</script>
{% endblock js_block %}

common/templates/doc_detail.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content%}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'common:doc_list' %}">Documentos</a></li>
    <li class="breadcrumb-item" active >Ver</li>
  </ol>
</nav>
<!-- OPPORTUNITY VIEW STARTS -->
<div class="main_container" id="maincontainer">
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body" id="datashow">
          <div class="panel-heading card-title view-pad text-center">
            <h5>
              Documento
            </h5>
            <a href="{% url 'common:edit_doc' doc_obj.id %}" class="btn btn-success edit">Editar</a>
          </div>
          <div class="row marl no-gutters">
            <div class="col-md-8">
              {% if doc_obj.title %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_title" data-name="title">Título</label>
                  <div class="contact_field" id="doc_title" data-name="name">{{ doc_obj.title }} </div>
                </div>
              </div>
              {% endif %}
              {% if doc_obj.status %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_status" data-name="status">Estado</label>
                  <div class="contact_field" id="doc_status" data-name="status">{{ doc_obj.status }} </div>
                </div>
              </div>
              {% endif %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_created_by" data-name="created_by">Creado por</label>
                  <div class="contact_field" id="created_by" data-name="created_by">{{ doc_obj.created_by }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_created_on" data-name="created_on">Fecha creación</label>
                  <div class="contact_field" id="created_on" data-name="created_on">{{ doc_obj.created_on|date:"d/m/Y P"}}</div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="profile_pic">
                {% if doc_obj.document_file %}
                <i class="{{file_type_code}}" aria-hidden="true" style="font-size:3rem;"></i>
                <!-- <a href="{{doc_obj.document_file.url}}" target="_blank">Download</a> -->
                <a style="display:block;" href="{% url 'common:download_document' doc_obj.id %}">Descargar</a></td>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- OPPORTUNITY VIEW ENDS -->
{% endblock %}

common/templates/imp_list.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- filter_row starts here -->
  <div class="row marl">
    <div class="col-lg-12 text-right">
      <span class="d-inline"><a href="{% url 'common:create_impuesto'%}" class="btn primary_btn">
        <i class="fa fa-plus"></i> Agregar Nuevo Impuesto</a>
      </span>

    </div>
  </div>
  <!-- filter_row ends here -->
  <div class="table_container_row row marl">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <div class="card-title list text-right">
            <span class="float-left">Impuestos - {% if show_pageitems %} {% show_pageitems %}{% else %} {{ impuestos|length }}{% endif %}</span>
            <span class="filter_toggle">
            <a style="padding:0px 10px;" href="#" class="primary_btn"></a>
            </span>
          </div>
          <div class="table-responsive ">
            <table class="table table-bordered table-striped table-condensed">
              <thead>
                {% if impuestos|length > 0 %}
                <tr>
                  <th width="30%">Impuestos</th>
                  <th width="25%">Tipo</th>
                  <th width="25%">Periodicidad</th>
                  <th width="20%">Acciones</th>
                </tr>
                {% endif %}
              </thead>
              <tbody>
                {% if per_page %}
                {% paginate per_page impuestos %}
                {% else %}
                {% paginate 10 impuestos %}
                {% endif %}
                {% for impuesto in impuestos %}
                <tr class="text-center">
                  <td><a href="{% url 'common:view_impuesto' impuesto.id %}">{{ impuesto.nombre }}</a></td>
                  <td>{{ impuesto.tipo |capfirst}}</td>
                  <td>{{ impuesto.periodicidad |capfirst }}</td>

                  <td class="actions">
                    <!-- Si ya ingresó aquí es administrador, no necesita otro filtro -->
                    <a href="{% url 'common:edit_impuesto' impuesto.id %}" class="btn btn-success edit action"><i class="fas fa-pencil-alt"></i>Editar</a>
                    <a href="{% url 'common:remove_impuesto' impuesto.id %}" class="btn btn-danger trash action">
                      <i class="fas fa-trash-alt"></i>Borrar</a>

                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% ifequal impuestos|length 0 %}
          <h6 class="text-center">No se encontraron Impuestos</h6>
          {% endifequal %}
          <div class="marl row text-center">
            {% show_pages %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- main_container ends here -->
{% endblock %}
{% block js_block %}
<script type="text/javascript">
  $('.trash').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('¿Está seguro que desea borrar?'))
      return;
    window.location = $(this).attr('href')
  });
</script>
<script>
$(document).ready(function(){
  var impuesto_id;
  $(".fa-passwd-reset").click(function(e){
    e.preventDefault();
    impuesto_id = $(this).attr('data-id')
    $("#password_eror").text("");
    $("#pass_change_div").modal();
  });
  $("#submit_password").click(function(e){
    e.preventDefault();
    if ($("#new_passwoord").val().length <4){
      $("#password_eror").text("* Las contraseñas deben tener al menos 4 carácteres!")
    }
    else{
      $("#password_eror").text("");
      $('#useer_id').val(impuesto_id);
      $("#chang_password_form").submit()
    }
  });
});
</script>
{% endblock js_block %}