common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin,
    EmpresasListView, EmpresaDetailView, CreateEmpresaView, UpdateEmpresaView,
    EmpresaDeleteView, change_empresa_status,
    ImpuestosListView, ImpuestoDetailView, CreateImpuestoView, UpdateImpuestoView,
    ImpuestoDeleteView, change_empresa_status
)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'common'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    # Empresas views
    path('empresas/list/', EmpresasListView.as_view(), name='empresas_list'),
    path('empresas/create/', CreateEmpresaView.as_view(), name='create_empresa'),
    path('empresas/<int:pk>/edit/', UpdateEmpresaView.as_view(), name="edit_empresa"),
    path('empresas/<int:pk>/view/', EmpresaDetailView.as_view(), name='view_empresa'),
    path('empresas/<int:pk>/delete/', EmpresaDeleteView.as_view(), name='remove_empresa'),

    # Impuestos views
    path('impuestos/list/', ImpuestosListView.as_view(), name='impuestos_list'),
    path('impuestos/create/', CreateImpuestoView.as_view(), name='create_impuesto'),
    path('impuestos/<int:pk>/edit/', UpdateImpuestoView.as_view(), name="edit_impuesto"),
    path('impuestos/<int:pk>/view/', ImpuestoDetailView.as_view(), name='view_impuesto'),
    path('impuestos/<int:pk>/delete/', ImpuestoDeleteView.as_view(), name='remove_impuesto'),


    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/list/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),
    path('empresa/status/<int:pk>/',
         change_empresa_status, name='change_empresa_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from contacts.views import (
    ContactsListView, CreateContactView, ContactDetailView,
    UpdateContactView, RemoveContactView,
    GetContactsView, AddCommentView, UpdateCommentView,
    DeleteCommentView)

app_name = 'contacts'

urlpatterns = [
    path('list/', ContactsListView.as_view(), name='list'),
    path('create/', CreateContactView.as_view(), name='add_contact'),
    path('<int:pk>/view/', ContactDetailView.as_view(), name="view_contact"),
    path('<int:pk>/edit/', UpdateContactView.as_view(), name="edit_contact"),
    path('<int:pk>/delete/',
         RemoveContactView.as_view(),
         name="remove_contact"),

    path('get/list/', GetContactsView.as_view(), name="get_contacts"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/',
         DeleteCommentView.as_view(),
         name="remove_comment"),

]

crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('facturas/', include('facturas.urls', namespace="facturas")),
    path('novedades/', include('novedades.urls', namespace="novedades")),
    path('tablas/', include('tablas.urls', namespace="tablas")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

tablas/urls.py
from django.urls import path
from .views import (
    HomeView,
    CreateFeriadoView, FeriadoDeleteView, FeriadoDetailView, FeriadosListView, UpdateFeriadoView,
    GanArt23ListView, GanArt90ListView, importar_feriado
)

app_name = 'tablas'

urlpatterns = [
    path('', HomeView.as_view(), name='tablas_home'),

    #Feriados
    path('feriados/', FeriadosListView.as_view(), name='feriados-list'),
    path('feriados/crear/', CreateFeriadoView.as_view(), name='feriado-create'),
    path('feriados/importar/', importar_feriado, name='feriado-import'),
    path('feriados/<int:pk>/', FeriadoDetailView.as_view(), name='feriado-detail'),
    path('feriados/<int:pk>/actualizar/', UpdateFeriadoView.as_view(), name='feriado-update'),
    path('feriados/<int:pk>/eliminar/', FeriadoDeleteView.as_view(), name='feriado-delete'),

    #Ganancias Art. 23
    path('g23/', GanArt23ListView.as_view(), name='ganart23-list'),

    #Ganancias Art. 90
    path('g90/', GanArt90ListView.as_view(), name='ganart90-list'),
]

contacts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from common.models import Address, User
from phonenumber_field.modelfields import PhoneNumberField


class Contact(models.Model):
    first_name = models.CharField(_("Nombre"), max_length=255)
    last_name = models.CharField(_("Apellido"), max_length=255)
    email = models.EmailField(unique=True)
    phone = PhoneNumberField(null=True, unique=True)
    address = models.ForeignKey(
        Address, related_name='adress_contacts',
        on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(
        User, related_name='contact_created_by',
        on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name

    class Meta:
        ordering = ['-created_on']

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load compress %}
{% load thumbnail %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Estudio Digital</title>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />

    {% compress css %}
    <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    <link href="{% static 'css/mention.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %} {% endblock %}
  </head>
  <body class="main_body_bg_color">
    <div class="wrapper">
      <!-- header starts here -->
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top">

          <a class="navbar-brand" href="{% url 'common:home' %}">Estudio Digital</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
          </button>
          {% if request.user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a class="nav-link" id="dashboard" href="{% url 'common:home' %}">Panel de Control</a></li>
              {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
              <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:users_list' %}">Usuarios</a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link" id="accounts" href="...">Novedeades</a></li>
              <li class="nav-item"><a class="nav-link" id="contacts" href="{% url 'contacts:list' %}">Contactos</a></li>
              <li class="nav-item"><a class="nav-link" id="resultados" href="{% url 'facturas:list' %}">Resultados</a></li>
              <li class="nav-item"><a class="nav-link" id="opportunities"href="...">Proyecciones</a></li>
              <li class="nav-item"><a class="nav-link" id="cases" href="...">Vencimientos</a></li>
              <li class="nav-item"><a class="nav-link" id="documents" href="{% url 'common:doc_list' %}">Documentos</a></li>
              {% if request.user.role == "ADMIN" or request.user.is_superuser %}
              <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:api_settings' %}">Configuraciones</a></li>
              {% endif %}
            </ul>
            <ul class="navbar-nav navbar-right my-2 my-lg-0">
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle abcd nav-link" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false" >
                {% if not request.user.profile_pic %}
                <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
                {% else %}
                {% thumbnail request.user.profile_pic "25x25" as im %}
                <img src="{{ im.url }}">
                {% endthumbnail %}
                {% endif %}
                <b class="caret"></b></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'common:profile' %}"><i class="fas fa-user"></i> Profile</a>
                  <a class="dropdown-item" href="{% url 'common:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </div>
              </li>
            </ul>
          </div>
          {% endif %}
        </nav>
      </header>
      <!-- header ends here -->
      <!-- main_container starts here -->
      <div id="mainbody" class="main_container" style="padding-top:65px;">
        <!-- breadcrumb starts here -->
        {% block breadcrumb %}
        {% endblock %}
        <!-- breadcrumb ends here -->
        {% block content %}
        {% endblock %}
      </div>
      <!-- main_container ends here -->
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment-with-locales.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
    {% block js_block %}
    {% endblock js_block %}
    <script type="text/javascript">
      $(document).ready(function(){
          word = window.location.pathname.split('/')[1]
          if(word == ""){
            $("#dashboard").addClass('active')
          }
          else{
            $('#' + word).addClass('active')
          }
      });
    </script>
  </body>
</html>

templates/change_password.html
{% extends 'sales/base.html' %}
{% load staticfiles %}

{% block content %}
<form id="add_form" method="POST" action="" novalidate>
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
         <div class="card-title">
          Change Password
        </div>
          <div class="row marl no-gutters">
            <div class="col-md-12">
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Old Password{% if change_password_form.CurrentPassword.field.required %} <span class="error">*</span>{% endif %}</label>
                  <input type="password" class="form-control" name="CurrentPassword" value="{{ request.POST.CurrentPassword }}" placeholder="Old Password">
                </div>
                <span class="error">{{ errors.CurrentPassword }}</span>
                {% if error %}
                <span class="error">{{ error }}</span>
                {% endif %}
              </div>
              {% endif %}
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">New Password {% if change_password_form.Newpassword.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="password" class="form-control" name="Newpassword" value="{{ request.POST.Newpassword }}" placeholder="New Password">
                </div>
                <span class="error">{{ errors.Newpassword }}</span>
              </div>
              {% endif %}
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Confirm New Password {% if change_password_form.confirm.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="password" class="form-control" name="confirm" value="{{ request.POST.confirm }}" placeholder="Confirm Password">
                </div>
                <span class="error">{{ errors.confirm }}</span>
              </div>
              {% endif %}
            </div>
          </div>
          <br>
          <div class="row marl buttons_row form_btn_row text-center">
            <button class="btn btn-default save" type="submit">Change Password</button>
            <button type="button" class="btn btn-default" onclick='window.open($(this).attr("href"),target = "_self")' href="{% url 'common:profile'%}" style="background:#099CBE;color:white">Cancel</button>
            <!--<button class="btn btn-default"><a href="{% url 'common:profile'%}" style="color:inherit;">Cancel</a></button>-->
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock content %}

templates/forgot_password.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django CRM</title>
    <!-- Bootstrap core CSS -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <!-- Custom styling plus plugins -->
    {% compress css %}
    <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %}{% endblock %}
  </head>
  <body class="login_register_body">
    <div class="container">
      <div class="row marl justify-content-center login_row">
        <div class="col-md-6 col-lg-6 col-xl-4">
          <div class="login_block">
            <div class="login_form_block">
              <div class="welcome">Forgot Password?</div>
              <form method="POST" action="">
                <div class="form-group">
                  <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
                </div>
                <div class="forgot">Back to login <a href="{% url "common:login" %}">Click Here?</a></div>
                <button type="submit" class="btn btn-danger">Reset Password</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/new_user.html
hello {{user.email}},

<p>Su cuenta ha sido creada exitosamente en Estudio Digtal {{created_by.email}}</p>

templates/profile.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content%}

<!-- OPPORTUNITY VIEW STARTS -->
  <div class="main_container" id="maincontainer">
    <div class="overview_form_block row marl justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body" id="datashow">
            <div class="panel-heading card-title view-pad text-center">
              <h5>
                Profile
                <!-- <span class="float-right" style="margin-top: 0px">
                  <div class="dropdown buttons_row">
                    <button class="btn btn-primary dropdown-toggle save" type="button" data-toggle="dropdown">Actions
                    <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><a href="#" >Edit</a></li>
                      <li class="delete_contact"><a href="#" id="remove_contact">Remove</a></li>
                    </ul>
                  </div>
                </span> -->
              </h5>
              <a href="{% url 'common:edit_user' user_obj.id %}" class="btn btn-success edit">Edit</a>
            </div>
            <div class="row marl no-gutters">
              <div class="col-md-8">
                {% if user_obj.first_name %}
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_name" data-name="name">Name</label>
                    <div class="contact_field" id="contact_name" data-name="name">{{ user_obj.first_name }} {{ user_obj.last_name }}</div>
                  </div>
                </div>
                {% endif %}
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_contact_account" data-name="name">Usuario</label>
                    <div class="contact_field" id="contact_account" data-name="name">{{ user_obj.username }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_email" data-name="name">Email</label>
                    <div class="contact_field" id="contact_email" data-name="name">{{ user_obj.email }}</div>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="profile_pic">
                  {% if user_obj.profile_pic %}
                    {% thumbnail request.user.profile_pic "125x125" as im %}
                    <img src="{{ im.url }}">
                    {% endthumbnail %}
                  {% else %}
                  <img src="{% static 'images/user.png' %}" alt="Micro profile pic" />
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- OPPORTUNITY VIEW ENDS -->
{% endblock %}

templates/root.html
{% load staticfiles %}
{% load compress %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Estudio Digital</title>
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <link href="https://cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
    <link href="https://cdn.quilljs.com/1.3.6/quill.core.css" rel="stylesheet">

    {% compress css %}
      <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
      <link href="{% static 'css/mention.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}

    {% block extralinks %} {% endblock %}
</head>
<body class="main_body_bg_color">
  <div class="wrapper">
    {% block header %}
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <!-- <a class="navbar-brand" href="{% url 'common:home' %}">Django CRM</a> -->
        <div class="dropdown">
          <a class="dropdown-toggle navbar-brand" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:#44535c">
            Estudio Digital
          </a>

          <div class="dropdown-menu mt-2" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="/">Principal</a>
            <a class="dropdown-item" href="...">Estado de Cuenta</a>
          </div>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
        {% if request.user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% block main_menu %}{% endblock %}

            <ul class="navbar-nav navbar-right my-2 my-lg-0">
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle abcd nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" >
                  {% if not request.user.profile_pic %}
                    <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
                  {% else %}
                    {% thumbnail request.user.profile_pic "25x25" as im %}
                      <img src="{{ im.url }}">
                    {% endthumbnail %}
                  {% endif %}
                  <b class="caret"></b>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
                  <a class="dropdown-item" href="{% url 'common:users_list' %}">Usuarios</a>
                  <a class="dropdown-item" href="{% url 'common:empresas_list' %}">Empresas</a>
                  <a class="dropdown-item" href="{% url 'common:impuestos_list' %}">Impuestos</a>
                  <a class="dropdown-item" href="{% url 'tablas:tablas_home' %}">Tablas</a>
                  <a class="dropdown-item" href="{% url 'common:api_settings' %}">Configuración</a>
                  {% endif %}
                  {% if request.user.email != "info@ceciliaprados.com.ar" %}
                  <a class="dropdown-item" href="/change-password/">Cambiar Contraseña</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'common:profile' %}">Perfil</a>
                  <a class="dropdown-item" href="{% url 'common:logout' %}">Salir</a>
                </div>
              </li>
            </ul>
          </div>
        {% endif %}
        </nav>
    </header>
      {% endblock %}

    <div id="mainbody" class="main_container" style="margin-top:65px;">
      {% block breadcrumb %}
      {% endblock %}

      {% block content %}
      {% endblock %}
    </div>
  </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>
<script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
<script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js"></script>

{% block js_block %}{% endblock js_block %}
<script type="text/javascript">
  $(document).ready(function(){
    word = window.location.pathname.split('/')[1]
    if(word == ""){
      $("#dashboard").addClass('active')
    }
    else{
      $('#' + word).addClass('active')
    }
  });
  /*
    Usage is very simple; to block user activity for the page:
      $.blockUI();

    Blocking with a custom message:
      $.blockUI({ message: '<h1><img src="busy.gif" /> Just a moment...</h1>' });

    Blocking with custom style:
      $.blockUI({ css: { backgroundColor: '#f00', color: '#fff'} });

    To unblock the page:
      $.unblockUI();

    If you want to use the default settings and have the UI blocked for all ajax requests, it's as easy as this:
      $(document).ajaxStart($.blockUI).ajaxStop($.unblockUI);
  */
</script>
</body>
</html>